services:
  backend:
    build:
      context: ./backend
    container_name: pokedex-fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    
  frontend:
    build:
      context: ./frontend
    container_name: pokedex-nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /app/node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    command: ["yarn", "dev"]